sudo: false
language: node_js
node_js:
  - "10"

branches:
  only:
    - master

install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - echo "" > ./out/.nojekyll
  - echo "palmtreecoding.com" > ./out/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: out
  on:
    branch: master
